version: "1"
services:
  mysql:
    image: jungboke/mysql:0.1
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  zookeeper:
    container_name: zookeeper
    image: jungboke/zookeeper:0.1
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: jungboke/kafka:0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.26.2.9
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
