spring:
  datasource:
    url: jdbc:mysql://localhost:3307/farm?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

# p6spy를 통한 SQL 로그 출력
decorator:
  datasource:
    p6spy:
      enable-logging: true

# p6spy의 출력 로깅 레벨을 debug로 설정
logging:
  level:
    p6spy: debug

cloud:
  aws:
    s3:
      bucket: maryfarm.bucket
    credentials:
      access-key: AKIA6GNIUYRRMAH6K36J
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false